name: skeletonizer
description: Converts already built widgets into skeleton loaders with no extra effort.
version: 2.1.1
homepage: https://github.com/Milad-Akarie/skeletonizer
screenshots:
  - description: 'Example of skeletonizer in action.'
    path: art/skeletonizer_logo_no_text.png
topics:
  - skeleton
  - shimmer-loading
  - skeleton-loader
  - loading

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.31.0-0.0.pre'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  alchemist: ^0.13.0
  coverage: ^1.15.0


flutter:
  uses-material-design: true

